version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - PYTHONPATH=/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts:/opt/airflow/plugins
      - SPARK_HOME=/opt/spark
      - SPARK_DRIVER_MEMORY=2g
      - PYSPARK_PYTHON=/usr/bin/python3
      - SPARK_CLASSPATH=/opt/airflow/jars/postgresql-42.6.0.jar #NEW TEST
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ~/Desktop:/host_desktop
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./typings:/opt/airflow/typings
      - ./jars/postgresql-42.6.0.jar:/opt/airflow/jars/postgresql-42.6.0.jar
    ports:
      - "8080:8080"
      - "4040:4040"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    build: .
    restart: always
    depends_on:
      - airflow-webserver
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - PYTHONPATH=/opt/airflow:/opt/airflow/dags:/opt/airflow/scripts:/opt/airflow/plugins
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ~/Desktop:/host_desktop
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./typings:/opt/airflow/typings
    command: airflow scheduler

volumes:
  postgres_data: